const data = [
	{
		id: 1,
		name: "Amritsar",
		info: "Golden Temple, the chief gurdwara, or house of worship, of Sikhism and the Sikhs’ most important pilgrimage site. It is located in the city of Amritsar, Punjab state, northwestern India.The first Harmandir Sahib was built in 1604 by Arjan, the fifth Sikh Guru, who symbolically had it placed on a lower level so that even the humblest had to step down to enter. He also included entrances on all four sides, signifying that it was open to worshippers of all castes and creeds. The foundation stone was laid by Mian Mīr, a Sufi Muslim saint from Lahore (now in Pakistan).",
		image: "./image1.jpg",
		price: "Darbar Sahib",
		url:"https://sgpc.net/sri-harmandir-sahib/",
	},
	{
		id: 2,
		name: "Amritsar",
		info: `The memorial at this site commemorates the 2000 Indians who were killed or wounded, shot indiscriminately by the British under the command of Gen Michael O”Dyer on April 13, 1919 while participating in a peaceful public meeting. This was one of the major incidents of India’s freedom struggle.The story of this appealing massacre is told in the Martyr’s Gallery at the site. A section of wall with bullet marks still visible is preserved along with the memorial well, in which some people jumped to escape. “The impossible men of India shall rise and liberate their mother land”, declared Mahatma Gandhi, after the Jallian Wala massacre.`,
		image: "./image2.webp",
		price: "Jallian Wala Bagh",
		url:"https://amritsar.nic.in/tourist-place/jallian-wala-bagh/",
	},
	{
		id: 3,
		name: "Pathankot",
		info: "Mini Goa Pathankot located on Dhar-Ranjit Sagar Dam Rd, Thara Uparla, Pathankot is the one of the most popular places to visit near Pathankot these days. Prime reason for gaining so much popularity is due to its location connected to two states of India that are Jammu and Punjab. Known as Purthu Mini Goa, Pathankot has a wide range of activities to enjoy with family and friends here in Pathankot. From Motorboat ride to horse ride and zipline are the highlights of the Picnic spot of Pathankot.You can visit this place before going to other popular places like Dharamshala, Dalhousie and Shimla.",
		image: "./image3.webp",
		price: "Mini Goa",
		url:"https://www.welovepathankot.com/mini-goa-pathankot/",
	},
	{
		id: 4,
		name: "Harike",
		info: "The sanctuary is a bird watchers paradise and attracts thousands of migratory birds during winter, some from as far off as Siberia and the Arctic. It is a refuge for a large number of resident and migratory birds. Some 45,000 ducks have been recorded here during the peak migratory season. The wigeon, common teal, pintail, shoveller and brahminy ducks are commonly seen during the winter. The lake is particularly famous for diving ducks, such as the crested pochard, common pochard and tufted ducks which occur in very large numbers. Around 375 bird species have been recorded; 40 species were long distance migrants which pass through or winter at Harike lake.",
		image: "./image15.jpg",
		price: "Harike Pattan",
		url:"https://ferozepur.nic.in/tourist-place/harike-wild-life-sanctuary-harike/"
	},
	{
		id: 5,
		name: "Amritsar",
		info: "The international border between India and Pakistan. The pomp and pageantry of the Beating Retreat and the Change of Guard within handshaking distance of the Indian and Pakistani forces makes for a most charming spectacle. Wagah, an army outpost on Indo-Pak border – between Amritsar and Lahore, is an elaborate complex of buildings, roads and barriers on both sides. The daily highlight is the evening “Beating the Retreat” ceremony. Soldiers from both countries march in perfect drill, going through the steps of bringing down their respective national flags.",
		image: "./image4.jpg",
		price: "Wagah-Border",
		url:"https://amritsar.nic.in/tourist-place/wagah-border/",
	},
	{
		id: 6,
		name: "Amritsar",
		info: "The Partition Museum comprehensively charts the Partition with a narrative arc that moves from the time before partition, proceeds to the independence movement, the early demands for separate countries, and ultimately the Partition and its consequences.The artefacts received by the Partition Museum include things that were of practical use brought across by people along with those that held sentimental value for them. From utensils, trunks and clothes, to a wedding sari, a jewellery box and a tin box, the Museum houses artefacts of the Partition belonging to people from diverse and different backgrounds.",
		image: "./image5.jpg",
		price: "The Partition Museum",
		url:"https://www.partitionmuseum.org/",
	},
	{
		id: 7,
		name: "Jalandhar",
		info: "Wonderland Theme Park, spread over 11 acres, is located about 6 km from Jalandhar bus terminus and 8 km from the railway station on Nakodar Road. This park offers many thrilling rides.The water rides include bumper cars, flying jets, horror house, boating, kiddies’ boating, play house, flying dragon and a slide splash. Among the several attractions, the wave pool is probably the most popular.There is an aqua dance floor, where visitors can dance to the tunes of the latest Punjabi songs. The dance floor is underneath a canopy, which has artificial clouds from where the water comes down like a rainfall. The Dry Park is open throughout the year, but the Water Park is closed during winters.",
		image: "./image6.webp",
		price: "Wonderland",
		url:"https://wonderlandthemepark.com/"
	},
	{
		id: 8,
		name: "kapurthala",
		info: "An emblem of Punjab, Pushpa Gujral Science City is an institution of fun and learning dedicated after the mother of late, I. K. Gujral, the 12th Prime Minister of India. Located midway Kapurthala and Jalandhar, the Science City sprawls in an area of 72 acres where you will find a fusion of modern, scientific temper in the agricultural background. If you have forgotten everything that you read in textbooks in your school, then a visit to the Science City in Kapurthala will be a fun reminder of all those things. Not just that, you will get simulation and visual experiences to take the thrill and fun up a notch.",
		image: "./image7.jpeg",
		price: "Science City",
		url:"http://pgsciencecity.org/"
	},
	{
		id: 9,
		name: "Kartarpur",
		info: "The Government of Punjab had conceptualized a mega project named as Jang-e-Azadi Memorial in commemoration of the unparalleled sacrifices of Indian’s & Punjabi’s for independence of India. The memorial complex for the heroes of the freedom struggle on 25 acres of land near Kartarpur.The Memorial disseminates knowledge about the rich cultural heritage of the State in the minds of youngsters. The site, which falls on the Jalandhar-Amritsar national highway, was carefully selected by the State Government keeping in mind its easy accessibility to visitors. Punjab Freedom Movement Memorial Foundation was formed by Government of Punjab for implementation of this prestigious project which completed it.",
		image: "./image8.jpg",
		price: "Jang-e-Azadi Memorial",
		url:"https://punjabtourism.punjab.gov.in/jang-e-azadi-kartarpur-jalandhar.php",
	},
	{
		id: 10,
		name: "Amritsar",
		info: "Gobindgarh Fort is a historic military fort located in the center of the city of Amritsar in the Indian state of Punjab. The Fort was until recently occupied by the Indian Army, but was opened to the public on 10 February 2017. Today the fort is being developed as a museum and theme park, as a repository of Punjab’s history.It is made of bricks and lime and is laid out in a square. Each of its corners has a parapet and two doors. It had 25 cannons mounted on its ramparts and has four bastions. The main entrance, Nalwa Gate, is named after Hari Singh Nalwa. Keller Gate is the back entrance. A tunnel runs towards Lahore.",
		image: "./image9.jpg",
		price: "Gobindgarh Fort",
		url:"https://www.fortgobindgarh.com/",
	},
	{
		id: 11,
		name: "Jalandhar",
		info: "Rangla Punjab Haveli in Jalandhar is a centre where the culture, traditional lifestyle and various art forms of Punjab are showcased. Ranging from the traditional dances of Bhangra and Gidda, to live puppet shows known as Kuthputli and even the showcasing of traditional Punjabi artefacts of phulkari and juttis, which you can take back home, this cultural museum and showhouse aims to guide you through all the glory of Punjabi culture and history.",
		image: "./image10.jpg",
		price: "Rangla Punjab Haveli",
		url:"https://www.haveli.co/rangla-punjab/",
	},
	{
		id: 12,
		name: "Patiala",
		info: "One of the awesome sight seen places in Patiala, Moti Bagh Palace, is situated near Gurdwara Motibagh and has been attracting hoards of tourists and the local people for its fabulous architecture and beautiful sculptures. This palace of architectural expertise has become the integral part of the history of Patiala. The construction was started when Maharaja Narinder Singh was the king of Patiala and the construction got completed during the reign of Maharaja Bhupinder Singh in the early years of 20th Century.",
		image: "./image14.jpg",
		price: "Moti Bagh Palace",
		url:"https://patiala.nic.in/tourist-place/moti-bagh-palace/",
	},
	{
		id: 13,
		name: "Amritsar",
		info: "Sadda Pind is a punjabi village living museum spread across 12 acres of land. It brings you a chance to experience authentic culture, colours and flavours of Punjab's traditional village in one place.Situated in the holy city of Amritsar, just 8 KM from Golden Temple and 7 KM from Airport, Sadda Pind offers a perfect setting for a weekend getaway or a short stay with family and friends.Sadda Pind is an endeavour to redefine punjabi culture and hospitality through commitment and world class service.",
		image: "./image11.jpg",
		price: "Sadda Pind",
		url:"https://www.saddapind.co.in/",
	},
	{
		id: 14,
		name: "Bathinda",
		info: "Experience the ultimate aquatic adventure at Bathinda's premier water park, India's Best Water Park. Nestled in the heart of Punjab, this exhilarating destination boasts an array of thrilling attractions designed to delight visitors of all ages. Prepare to be swept away by the excitement of our Double Wave Pool, where you can ride the waves and soak up the sun in style. Feel the rush of adrenaline as you plunge down the Carnival Ship Slides or race against friends on our Family, Solo, and Couple Slides.",
		image: "./image12.jpg",
		price: "Punjoy",
		url:"https://www.punjoy.com/",
	},
	{
		id: 15,
		name: "Ludhiana",
		info: "The Punjab Agricultural University (PAU) Museum, situated in Ludhiana, Punjab, India, is a notable institution dedicated to preserving and showcasing the rich agricultural heritage of Punjab and the contributions of the Punjab Agricultural University to agricultural research, education, and development. The museum houses a diverse collection of artifacts, exhibits, and displays related to agriculture, horticulture, animal husbandry, and rural life in Punjab. Visitors to the museum can explore galleries featuring agricultural implements, tools, machinery, and models representing various aspects of farming practices and techniques.",
		image: "./image13.jpg",
		price: "PAU Museum",
		url:"https://www.touristplaces.net.in/ludhiana-pb/punjab-agricultural-university-pau-museum/",
	},
	{
		id: 16,
		name: "Ludhiana",
		info: "Hardy’s World offers a variety of rides and attractions for all ages and tastes, from roller coasters and Ferris wheel to water slides and wave pool. Whether you want to experience the adrenaline rush of the dry rides, or splash into the refreshing fun of the wet rides, Hardy’s World has something for everyone. Summer is the peak season for Hardy’s World, as most people flock to the water park to beat the heat and enjoy the cool and refreshing rides.",
		image: "./image16.webp",
		price: "Hardy's World",
		url:"https://hardysworld.com/",
	},
];

export default data;